print "Loading Event IDs"

EVT_STARTUP = -1
EVT_SHUTDOWN = -2
EVT_CONNECTED = -3
EVT_DISCONNECTED = -4
EVT_CLEAR_BINDS = -5
EVT_THREAD = -6

-- InSim packet types
ISP_NONE = 0
ISP_ISI =  1 
ISP_VER =  2
ISP_TINY =  3
ISP_SMALL =  4
ISP_STA =  5
ISP_SCH =  6
ISP_SFP =  7
ISP_SCC =  8
ISP_CPP =  9
ISP_ISM = 10
ISP_MSO = 11
ISP_III = 12
ISP_MST = 13
ISP_MTC = 14
ISP_MOD = 15
ISP_VTN = 16
ISP_RST = 17
ISP_NCN = 18
ISP_CNL = 19
ISP_CPR = 20
ISP_NPL = 21
ISP_PLP = 22
ISP_PLL = 23
ISP_LAP = 24
ISP_SPX = 25
ISP_PIT = 26
ISP_PSF = 27
ISP_PLA = 28
ISP_CCH = 29
ISP_PEN = 30
ISP_TOC = 31
ISP_FLG = 32
ISP_PFL = 33
ISP_FIN = 34
ISP_RES = 35
ISP_REO = 36
ISP_NLP = 37
ISP_MCI = 38
ISP_MSX = 39
ISP_MSL = 40
ISP_CRS = 41
ISP_BFN = 42
ISP_AXI = 43
ISP_AXO = 44
ISP_BTN = 45
ISP_BTC = 46
ISP_BTT = 47

-- The fourth byte of IS_TINY packets is one of these
TINY_NONE = 0
TINY_VER = 1
TINY_CLOSE = 2
TINY_PING = 3
TINY_REPLY = 4
TINY_VTC = 5
TINY_SCP = 6
TINY_SST = 7
TINY_GTH = 8
TINY_MPE = 9
TINY_ISM = 10
TINY_REN = 11
TINY_CLR = 12
TINY_NCN = 13
TINY_NPL = 14
TINY_RES = 15
TINY_NLP = 16
TINY_MCI = 17
TINY_REO = 18
TINY_RST = 19
TINY_AXI = 20
TINY_AXC = 21

-- The fourth byte of IS_SMALL packets is one of these
SMALL_NONE = 0
SMALL_SSP = 1
SMALL_SSG = 2
SMALL_VTA = 3
SMALL_TMS = 4
SMALL_STP = 5
SMALL_RTP = 6
SMALL_NLI = 7

-- Voting actions
VOTE_NONE = 0 -- no vote
VOTE_END = 1 -- end race
VOTE_RESTART = 2 -- restart
VOTE_QUALIFY = 3 -- qualify

-- ISP_ISI Flags
ISF_RES_0 = 1
ISF_RES_1 = 2
ISF_LOCAL = 4
ISF_MSO_COLS = 8
ISF_NLP = 16
ISF_MCI	= 32

-- Button locations
IS_X_MIN = 0
IS_X_MAX = 110

IS_Y_MIN = 30
IS_Y_MAX = 170

-- Button Flags
INST_ALWAYS_ON = 128

ISB_C1 = 1
ISB_C2 = 2
ISB_C4 = 4
ISB_CLICK = 8
ISB_LIGHT = 16
ISB_DARK = 32
ISB_LEFT = 64
ISB_RIGHT = 128

ISB_LMB = 1
ISB_RMB	= 2
ISB_CTRL = 4
ISB_SHIFT = 8

BFN_DEL_BTN = 0
BFN_CLEAR = 1
BFN_USER_CLEAR = 2
BFN_REQUEST = 3
